name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '24.3'
          - '24.5'
          - '25.3'
          - '26.3'
          - '27.1'
          - 'snapshot'
        include:
          - emacs_version: 'snapshot'
            allow_failure: true
    steps:
    - uses: actions/checkout@v1
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Run tests
      if: matrix.allow_failure != true
      run: 'make test-batch'

    - name: Run tests (allow failure)
      if: matrix.allow_failure == true
      run: 'make test-batch || true'
